import './js/mobile-menu';
import './js/modal-buy';
import './js/anchor-scroll';
import './js/header-scrol';
import './js/btn-up';
import './js/reviews-pagination';
import './js/counter-hero';
import './js/counter-advantages';
import './js/gallery-slider';
